name: flutter_application_8
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  dio:
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  lottie: ^3.1.2
  get:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie_json/

  fonts:
    - family: Harmony
      fonts:
        - asset: assets/harmony_fonts/HarmonyOS_Sans_SC_Regular.ttf
